"""Full 14-parameter box certification by a first-order (mean-value) interval form.

For a box P = prod [p_i - d_i, p_i + d_i] around the m = 0.21 witness and any smooth
G(X(p), p) with X(p) the coexistence prey level defined implicitly by
    F(X, p) := g_DA(X; p) - (chi(p) X - nu(p)) = 0,   F_X != 0 on the box,
the mean-value theorem gives the rigorous enclosure
    G(P) subset G(c) + sum_i (dG/dp_i)(P_hull) * [-d_i, d_i],
    dG/dp_i = G_{p_i} - G_X F_{p_i} / F_X,
where G(c) is the interval evaluation at the box centre (tight) and the total derivatives are
interval-evaluated over the hull (X_box x P) with X_box a coarse verified enclosure of X(P)
(interval Newton).  Every expression is generated by SymPy from the model and evaluated with
mpmath.iv (outward rounding, 50 digits); the C-11 fractional certificate Phi > rho and the
C-10 certificate kappa_hi < L(beta_lo) (certified T_alpha bracket at the lower beta corner,
monotone in beta) are applied to the resulting enclosures.
Output: appended to computations/results/DOUBLE_ALLEE_INTERVAL_BOX.json under "B_meanvalue".
"""
from __future__ import annotations

import json
import os
import sys
import time

import mpmath as mp
import sympy as sp
from mpmath import iv

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RES = os.path.join(ROOT, "computations", "results")
from fdsn.double_allee import PARAM_NAMES, Params, chief_witness, quadratic_coeffs, with_m  # noqa: E402
from fdsn.interval_cert import certify_threshold_logit  # noqa: E402

iv.dps = 50
mp.mp.dps = 50
ALPHA = "0.9"

# ----------------------------------------------------------------- symbolic model
X = sp.Symbol("X")
p = sp.symbols(" ".join(PARAM_NAMES))
a, K, r, m, q1, q2, h, e1, e2, e3, mu1, mu2, c1, c2 = p
g = r / (X + a) * (1 - X / K) * (X - m)
Delta = c1 * c2 + e3 * h ** 2
chi = (e1 * c2 * q1 ** 2 + e2 * c1 * q2 ** 2 + h * q1 * q2 * (e1 * e3 - e2)) / Delta
nu = (mu1 * (q1 * c2 + q2 * e3 * h) + mu2 * (q2 * c1 - q1 * h)) / Delta
F = g - (chi * X - nu)
A1 = e1 * q1 * X - mu1; A2 = e2 * q2 * X - mu2
Yx = (c2 * A1 - h * A2) / Delta
Zx = (e3 * h * A1 + c1 * A2) / Delta
s = -sp.diff(g, X)
beta12 = 1 + e1 * q1 ** 2 / (s * c1); beta13 = 1 + e2 * q2 ** 2 / (s * c2); beta23 = 1 + e3 * h ** 2 / (c1 * c2)
kappa = beta12 + beta13 + beta23 - 2 + h * q1 * q2 * (e1 * e3 - e2) / (s * c1 * c2)
T1 = (sp.sqrt(beta12) + sp.sqrt(beta13) + sp.sqrt(beta23)) ** 2
rho = sp.Symbol("rho_alpha")          # passed as a zero-width interval argument (no sympy constants in the lambdas)
RHO_IV = (1 - 2 * iv.cos(iv.mpf(ALPHA) * iv.pi / 2)) ** 2
TARGETS = {"Y": Yx, "Z": Zx, "s": s, "X_minus_m": X - m, "K_minus_X": K - X, "kappa_minus_T1": kappa - T1,
           "Phi_minus_rho": T1 / kappa - rho, "beta12": beta12, "beta13": beta13, "beta23": beta23, "kappa": kappa}

MODS = [{"sqrt": iv.sqrt}]


def lam(expr):
    f = sp.lambdify((X,) + p + (rho,), expr, modules=MODS)
    return lambda Xv, *pv: f(Xv, *pv, RHO_IV)


F_X = lam(sp.diff(F, X))
F_p = [lam(sp.diff(F, pi)) for pi in p]
TOTAL = {}
for name, G in TARGETS.items():
    GX = sp.diff(G, X); Gp = [sp.diff(G, pi) for pi in p]
    TOTAL[name] = (lam(G), lam(GX), [lam(v) for v in Gp])


def lo(x):
    return mp.mpf(x.a)


def hi(x):
    return mp.mpf(x.b)


def coarse_X(center, box):
    """Coarse verified enclosure of X(P): interval Newton on the aggregated quadratic (as in the 1-D script)."""
    Pb = Params(*box)
    A_, B_, C_ = quadratic_coeffs(Pb)
    Pc = Params(*center)
    Ac, Bc, Cc = quadratic_coeffs(Pc)
    xh = (Bc + mp.sqrt(Bc * Bc - 4 * Ac * Cc)) / (2 * Ac)
    for w in (mp.mpf("1e-4"), mp.mpf("1e-3"), mp.mpf("1e-2"), mp.mpf("0.05"), mp.mpf("0.2")):
        Xb = iv.mpf([xh - w, xh + w])
        fp = 2 * A_ * Xb - B_
        if not (lo(fp) > 0 or hi(fp) < 0):
            continue
        xi_ = iv.mpf(xh)
        Xn = xi_ - (A_ * xi_ * xi_ - B_ * xi_ + C_) / fp
        if lo(Xn) > lo(Xb) and hi(Xn) < hi(Xb):
            return Xn, xh
    return None, xh


def enclose(name, center, box, Xb, xc):
    """Mean-value enclosure of TARGETS[name] over the box."""
    Gf, GXf, Gpf = TOTAL[name]
    cen = Gf(iv.mpf(xc), *[iv.mpf(v) for v in center])          # not exactly at X(c) -- see note below
    # exact centre: X(c) is enclosed by a point-Newton step; use the tight interval Xc
    return cen


def certify_box(center, deltas, cache):
    box = [iv.mpf([c * (1 - d), c * (1 + d)]) for c, d in zip(center, deltas)]
    Xb, xh = coarse_X(center, box)
    if Xb is None:
        return {"ok": False, "fail": "coarse X enclosure failed"}
    # tight enclosure of X at the centre: interval Newton on F with point parameters
    cen_iv = [iv.mpf(v) for v in center]
    fx_c = F_X(iv.mpf([xh - mp.mpf("1e-6"), xh + mp.mpf("1e-6")]), *cen_iv)
    Fc = lam(F)(iv.mpf(xh), *cen_iv)
    Xc = iv.mpf(xh) - Fc / fx_c
    if not (lo(Xc) > xh - mp.mpf("1e-6") and hi(Xc) < xh + mp.mpf("1e-6")):
        return {"ok": False, "fail": "centre X Newton did not contract"}
    # F_X on the hull must exclude zero (IFT / mean-value validity)
    fxh = F_X(Xb, *box)
    if not (lo(fxh) > 0 or hi(fxh) < 0):
        return {"ok": False, "fail": "F_X contains 0 on the hull"}
    fph = [fp(Xb, *box) for fp in F_p]
    dX = [-v / fxh for v in fph]                                   # dX/dp_i over the hull
    out = {"ok": True, "X_center": (lo(Xc), hi(Xc)), "X_hull": (lo(Xb), hi(Xb))}
    enc = {}
    for name in TARGETS:
        Gf, GXf, Gpf = TOTAL[name]
        val = Gf(Xc, *cen_iv)
        GX = GXf(Xb, *box)
        for i, (gp, ci, di) in enumerate(zip(Gpf, center, deltas)):
            dG = gp(Xb, *box) + GX * dX[i]
            val = val + dG * iv.mpf([-ci * di, ci * di])
        enc[name] = (lo(val), hi(val))
    out["enclosures"] = {k: (mp.nstr(v[0], 15), mp.nstr(v[1], 15)) for k, v in enc.items()}
    checks = {"Y>0": enc["Y"][0] > 0, "Z>0": enc["Z"][0] > 0, "X>m": enc["X_minus_m"][0] > 0, "X<K": enc["K_minus_X"][0] > 0,
              "s>0": enc["s"][0] > 0, "kappa-T1>0": enc["kappa_minus_T1"][0] > 0, "C11: Phi-rho>0": enc["Phi_minus_rho"][0] > 0}
    # strict-P: with s > 0 all order-2 minors are positive; q = kappa s c1 c2 > 0 from kappa > T1 > 0
    key = tuple(mp.nstr(enc[b][0], 40) for b in ("beta12", "beta13", "beta23"))
    if key not in cache:
        c = certify_threshold_logit(list(key), ALPHA, dps=40)
        cache[key] = c["L"] if c.get("certified") else None
    L = cache[key]
    checks["C10: kappa_hi < L(beta_lo)"] = bool(L is not None and enc["kappa"][1] < L)
    out["T_alpha_L_at_beta_lo"] = mp.nstr(L, 20) if L is not None else None
    out["checks"] = checks
    out["ok"] = all(checks[k] for k in checks if not k.startswith("C10")) and (checks["C10: kappa_hi < L(beta_lo)"] or checks["C11: Phi-rho>0"])
    out["fail"] = "" if out["ok"] else [k for k, v in checks.items() if not v]
    return out


def main():
    t0 = time.time()
    Pw = with_m(chief_witness(lambda v: mp.mpf(v)), mp.mpf("0.21"))
    center = Pw.as_list()
    cache = {}
    results = []
    largest = None
    for delta in ("5e-3", "2e-3", "1e-3", "5e-4", "2e-4", "1e-4"):
        d = mp.mpf(delta)
        res = certify_box(center, [d] * 14, cache)
        results.append({"delta_relative": delta, **{k: v for k, v in res.items() if k != "enclosures"},
                        "enclosures": res.get("enclosures")})
        print(delta, res["ok"], res.get("fail"), res.get("enclosures", {}).get("kappa_minus_T1"), res.get("enclosures", {}).get("Z"))
        if res["ok"] and largest is None:
            largest = delta
            break
    # anisotropic box: half-widths from the float sensitivities (larger in insensitive directions)
    sens = {"a": 3.7, "K": 15.7, "r": 10.3, "m": 3.1, "q1": 21.8, "q2": 11.0, "h": 10.7, "e1": 23.8, "e2": 1.4, "e3": 12.8,
            "mu1": 10.9, "mu2": 1.2, "c1": 10.8, "c2": 10.2}      # |d(kappa-T1)/dlog p| at the witness (float, adversarial script)
    aniso = []
    for scale in ("0.6", "0.4", "0.25", "0.15", "0.1"):
        sc = mp.mpf(scale) * mp.mpf("0.1457") / sum(sens.values())
        deltas = [min(mp.mpf("0.02"), sc * sum(sens.values()) / (14 * sens[n])) for n in PARAM_NAMES]
        res = certify_box(center, deltas, cache)
        aniso.append({"scale": scale, "deltas": {n: mp.nstr(dd, 5) for n, dd in zip(PARAM_NAMES, deltas)}, "ok": res["ok"], "fail": res.get("fail"),
                      "kappa_minus_T1_enclosure": res.get("enclosures", {}).get("kappa_minus_T1"), "checks": res.get("checks")})
        print("aniso", scale, res["ok"], res.get("fail"))
        if res["ok"]:
            break
    path = os.path.join(RES, "DOUBLE_ALLEE_INTERVAL_BOX.json")
    d = json.load(open(path)) if os.path.exists(path) else {}
    d["B_meanvalue"] = {"method": __doc__.strip().splitlines()[0], "isotropic_boxes": results, "largest_isotropic_delta_certified": largest,
                        "anisotropic_boxes": aniso, "seconds": round(time.time() - t0, 1),
                        "labels": "C-11 certificate rigorous/unconditional; C-10 certificate conditional on C-15 Thm 1 (+ C-13 monotonicity)"}
    if largest:
        d["B_largest_certified_delta"] = largest
        d["B_statement"] = (f"every parameter vector in the box p_i in [p_i(1-{largest}), p_i(1+{largest})] (all 14 biological parameters, "
                            "around the m=0.21 witness) has a CERTIFIED positive coexistence equilibrium that is strict-P, not Hurwitz "
                            "D-stable (kappa > T1) and in F_0.9 (kappa < T_0.9(beta)): a full-dimensional certified genuinely fractional box")
    json.dump(d, open(path, "w"), indent=2, default=str)


if __name__ == "__main__":
    main()
